"""initial migration

Revision ID: bff6f4365aab
Revises: 
Create Date: 2026-03-15 22:06:04.731115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bff6f4365aab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_path', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.Enum('txt', name='sourcetype'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', content)", persisted=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chunks_document_position', 'chunks', ['document_id', 'position'], unique=False)
    op.create_index('ix_chunks_search_vector', 'chunks', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('old_text', sa.Text(), nullable=False),
    sa.Column('new_text', sa.Text(), nullable=False),
    sa.Column('occurrence', sa.Integer(), nullable=False),
    sa.Column('old_text_offset', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='changestatus'), nullable=False),
    sa.Column('document_version', sa.Integer(), nullable=False),
    sa.Column('change_group_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_changes_change_group_id'), 'changes', ['change_group_id'], unique=False)
    op.create_index('ix_changes_document_created', 'changes', ['document_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_changes_document_created', table_name='changes')
    op.drop_index(op.f('ix_changes_change_group_id'), table_name='changes')
    op.drop_table('changes')
    op.drop_index('ix_chunks_search_vector', table_name='chunks', postgresql_using='gin')
    op.drop_index('ix_chunks_document_position', table_name='chunks')
    op.drop_table('chunks')
    op.drop_table('documents')
    # ### end Alembic commands ###
